# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a37cb2efbc2d4c8ce6083219010e6cac10be3f0c5b8379d5f9e816210081b555e720a4e1500c9d5ebd080619202a37e090a80cfbe0496153f974d8178888e167

test:
  secret_key_base: fbb1ab4c2d02e5dea5d33a07b92a32ffa34d2a7c9ea9663ad0e18e95dd3f839e7793029ee8fa8c13b6ef2b0c76990a77eaa0cab22b7adcb6da055dd96d49757e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
